"""The linkstation component constants."""



DEFAULT_NAS_LANGUAGE = 'en'
DEFAULT_PROTOCOL = 'http'

LINKSTATION_API_ENDPOINT = 'dynamic.pl'
LINKSTATION_API_FUNCTION_PARAM_NAME = 'bufaction'
LINKSTATION_API_LOGIN_FUNC_NAME = 'verifyLogin'
LINKSTATION_API_GETSETTINGS_FUNC_NAME = 'getRootSettings1'
LINKSTATION_API_REBOOT_FUNC_NAME = 'shutRestartLS'
LINKSTATION_API_GETALLDISK_FUNC_NAME = 'getDiskAllList'

LINKSTATION_API_ACTION_PARAM_NAME = 'action'
LINKSTATION_API_REBOOT_ACTION_NAME = 'reboot'


LINKSTATION_API_PARAM_USERNAME = 'user'
LINKSTATION_API_PARAM_PASSWORD = 'password'

LINKSTATION_API_REPONSE_DATA_NAME = 'data'

DEFAULT_BINARY_SENSOR_NAME = "REST Binary Sensor"
DEFAULT_SENSOR_NAME = "REST Sensor"
CONF_JSON_ATTRS = "json_attributes"
CONF_JSON_ATTRS_PATH = "json_attributes_path"

REST_IDX = "rest_idx"
PLATFORM_IDX = "platform_idx"

COORDINATOR = "coordinator"
REST = "rest"

REST_DATA = "rest_data"

METHODS = ["POST", "GET"]