"""The LinkStation constants."""

from typing import Final

DEFAULT_NAS_LANGUAGE: Final = "en"
DEFAULT_PROTOCOL: Final = "http"
DEFAULT_DATA_CACHE_SECONDS: Final = 10 #seconds

LINKSTATION_API_ENDPOINT = "dynamic.pl"
LINKSTATION_API_FUNCTION_PARAM_NAME = "bufaction"
LINKSTATION_API_LOGIN_FUNC_NAME = "verifyLogin"
LINKSTATION_API_GETSETTINGS_FUNC_NAME = "getRootSettings1"
LINKSTATION_API_REBOOT_FUNC_NAME = "shutRestartLS"
LINKSTATION_API_GETALLDISK_FUNC_NAME = "getDiskAllList"

LINKSTATION_API_ACTION_PARAM_NAME = "action"
LINKSTATION_API_REBOOT_ACTION_NAME = "reboot"

LINKSTATION_COOKIE_PREFIX = "webui_session_"
LINKSTATION_COOKIE_SEPARATOR = "_"

LINKSTATION_API_PARAM_USERNAME = "user"
LINKSTATION_API_PARAM_PASSWORD = "password"

LINKSTATION_API_REPONSE_SUCCESS_STATUS = "success"
LINKSTATION_API_REPONSE_DATA_ELEMENT = "data"
LINKSTATION_API_REPONSE_DATA_GENERALINFO_ELEMENT = "generalInfo"
LINKSTATION_API_AUTH_REPONSE_SID = "sid"
LINKSTATION_API_AUTH_REPONSE_PAGEMODE = "pageMode"
LINKSTATION_API_REPONSE_DATA_DISK_ELEMENT = "disk"
LINKSTATION_API_REPONSE_DATA_DISK_STATUS = "status"
LINKSTATION_API_REPONSE_DATA_DISK_STATUS_REMOVE = "remove"
LINKSTATION_API_REPONSE_DATA_DISK_STATUS_DISCONNECT = "disconnect"
LINKSTATION_API_REPONSE_DATA_DISK_CAPACITY = "capacity"
LINKSTATION_API_REPONSE_DATA_DISK_PCT_USED = "percentUsed"
LINKSTATION_API_REPONSE_DATA_DISK_AMOUNT_USED = "amountUsed"
LINKSTATION_API_REPONSE_DATA_DISK_UNITNAME = "unitName"

